FROM node:24-alpine
RUN corepack enable
WORKDIR /app

COPY package.json pnpm-workspace.yaml pnpm-lock.yaml turbo.json ./
COPY packages/ packages/
COPY apps/ apps/

RUN pnpm install --frozen-lockfile
RUN pnpm --filter api exec prisma generate

CMD ["sh", "-c", "pnpm --filter api exec prisma migrate dev && pnpm --filter api dev"]
